on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        glium: ["", "glium-support"]
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --features '${{ matrix.glium }}'
      - run: cargo test --features '${{ matrix.glium }}'
      - run: cargo clippy --features '${{ matrix.glium }}' --no-deps -- -D warnings
      - run: cargo fmt -- --check

  sample:
    name: Test sample app
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        project: [sampleapp, sampleapp-vulkano]
    if: matrix.os != 'windows-latest' || matrix.project != 'sampleapp-vulkano'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: cargo build -p '${{ matrix.project }}'
      - run: cargo test -p '${{ matrix.project }}'
      - run: cargo clippy -p '${{ matrix.project }}' --no-deps -- -D warnings
      - run: cargo fmt -p '${{ matrix.project }}' -- --check
