on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build
      - run: cargo test
      - run: cargo clippy --workspace --no-deps -- -D warnings
      - run: cargo fmt -- --check

  sample:
    name: Test sample app
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: cargo build -p sampleapp
